@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList {
  ..private..
  - privateField: string
  ~ packagePrivateField: number
  ..protected..
  # protectedField: string
  ..public..
  + publicField: number
  --
  ..private..
  - privateMethod(): string
  ~ packagePrivateMethod(): number
  ..protected..
  # protectedMethod(): string
  ..public..
  + publicMethod(): number
}

@enduml
